language: java
script: mvn clean package -Pprod
addons:
  ssh_known_hosts: 107.170.29.174
before_deploy:
- openssl aes-256-cbc -K $encrypted_4a21bc166b29_key -iv $encrypted_4a21bc166b29_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync --quiet $TRAVIS_BUILD_DIR/target/thebuyback*.war $USER@$HOST:~/thebuyback_$(date
    +%y-%m-%d-%H-%M).war && ssh-agent -k
  on:
    branch: master
env:
  secure: FspR19rh8TuWHoYLd96ihqcFpT8Ou3QQVk5f7TzhY1ZstOv8xC7dalsHSwXbOOpE07kKr6oQKSx3WO4KWHQ45J0Imb8E0h3II0ST1wtXBC2bQ7Vx57ezanfVh3rQaboMX2Yb0rPYDXA54AXQGHNBlAmMv8ujVyzyrKk5WstdarQgtd2sUem3QAN9UzZ/V8+C6OfjiMlfrmZUXZ76mcjJckE+UPfytFrVi3Pwi9WggIIPLwun49GjVLfgmbSnMWfAf8N/j/Qwcbovgh5AgbIj7U4RRDVSPSsqCdiNLoL9YEYZnQy+UID0JeouoYdV/dG7ejT9cJbdtAErm0Uua4z9EFf+SY7mBlU06tHIS/k2tEJTGkUG8aa3r818zEKL4dNAFFQq4rs318TbxcjTAaj9PxWk5dcCk6+HXLbkNYA8cIl6pdipnpxth06cPvuSQZas9IRZ+is9EzkOW6v3IJQgCv5jPJWYy4Ay+yJHvPtsXElgg8yRcEELikukqZf+JW/QerEi2MK99WcE/bCyX54fJ/PkoYEFcirxOwYlPIjWI7g1Qm8fFQd25ghEATaCDxTd8jxyJMwAlTmykOAo17+u08xKOIX7tj5ibce24eUe728VIIPXPYlaN4xsYb4HYUjybgsPJJkkHEkxhH+UqmliCGotg+1euLB8Atekwz4Q5CI=
