language: java
script: mvn clean package -Pprod
addons:
  ssh_known_hosts: 107.170.29.174
before_deploy:
- openssl aes-256-cbc -K $encrypted_4a21bc166b29_key -iv $encrypted_4a21bc166b29_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync --quiet $TRAVIS_BUILD_DIR/target/thebuyback*.war $USER@$HOST:~/thebuyback_$(date
    +%y-%m-%d-%H-%M).war && ssh-agent -k
  on:
    branch: master
env:
  secure: rVHkZ6EP04kp22w24b8e7DtZXcs691vuzBU2sAQjOfL3x5XlTG99FBaTOZPHmHkpLWla49TURsdr4/Syke6si3z95lYCj3HK8x7wmBHpyNZhjNk7SMiS4KUGfUmbkCvw98hSsR8yJv8TMqp/+2CYP4u6zLPUiDtFiZ/F93OhO1qkVm+cRVDOGBXYyPMOTRdjckWgpdMk0Kss2FA5EoRoOEDqgQfXhPAR7sRl0yNExcjURvMz9z75D4QY/cOqBTOidk4y310zZsI5f0DUWGOZEVpYLol1qnBCK5gH61kbmyCKluxUHEmmBWHCfji5zZLSb2+7lzYNI37a48N3GwO6TteLO4o0PkzXX5jcWOHPHi5tU4sENAdrwpPMV8tVFYFUMeU+v01y+IkYusXP6igLB41fNUaSbfGKkqM0f14XuGhLHVyYKeqbmNjNsiHvTX4+yXCkXYK7xHDBJNNBf+LrjapLM8Q5X2KGeY7CLu/XwCbFg37oqOS8fJLspw4kQW5DV5+C6NIw3tRSXmlrMf9umAnVRS9SoSEZBV2dXq4xrCQCHiwkGk5pBd/7KfXdoqxyeXLJotWYYes6vOiM9ZLXlwhnH800nPGx9/8U19/XrLkBuPyCT+vWwIeUiinr6c2Ta+bDVBhtHo/n5Zs1VQvEBiPxwrv8NYSB9rRFeA7B19U=
