language: java
script: mvn clean package -Pprod
addons:
  ssh_known_hosts: 107.170.29.174
before_deploy:
- openssl aes-256-cbc -K $encrypted_4a21bc166b29_key -iv $encrypted_4a21bc166b29_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
#  added ssh-agent -k to release the agent so the build can succeed, see https://github.com/travis-ci/travis-ci/issues/8082
  script: rsync --quiet $TRAVIS_BUILD_DIR/target/thebuyback*.war $USER@$HOST:~/thebuyback_$(date
    +%m-%d-%y-%H-%M).war && ssh-agent -k
  on:
    branch: master
env:
  secure: OS95TgreueGCPfpOyYnpyj7BbDqJrTmtZVPuAKLU9gQ4h1ha3d8RNi6vPG8qpD3OmpD9LsFomGD22MP3wpxj4Al/8WsW8hIOdbjztx6viKNI2zhx0uY48jiL8U3ihsM+wBwZdV0O4gOOoRK4jV/NuGz5WXze5UVR0BXt+V+LFQpJmfgoJU/1sJ9oD7v3sHU8RQhAiUAQWYZWa2qpVI2A4UF+wWwmrekrGtRA9MxNG1uDK+tPvZD7YVZdJpmpq1UpB4AzhVau+fBMSUDvKTfsl/jRL1i4aa3WiUKGk2vZbcQnai9jQhHYptrTJDXAZ5WDwJ2ISRxjCnaECA8MMEywJdyV2oTLg8HR3IzEwqzFgkotaLsmnpL2cMBu+PxrS6UpEwtPzQFvsuRJCoDKDJBBKBN/Tip7nOijqI+aPHXj87yjIOi/1EMOeEbb6L+6tgerlRVZEbJhozHCWtVQSSaHpZVBRxU0UiSilSXWJTUxLLZD3+P9DbzI8XPFzm55Z17mwIymXoGJefx3CU0z2ULDKiR+wUzAL7JpWF9x7f/ZysUGCX3ak8w1uD/L7LhhDGBcKWEZGbs7vUpHOVGbyD59YkTzJ+IKtrS2B4zYHhQ9IO/0B32w5Dw7Q4IU5nMFYlCipKQIObMtUeRZcgGXDm9GdZwqAHKlxciYMspzlmjr7lY=
