language: java
script: mvn clean package -Pprod
addons:
  ssh_known_hosts: 107.170.29.174
before_deploy:
- openssl aes-256-cbc -K $encrypted_4a21bc166b29_key -iv $encrypted_4a21bc166b29_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync --quiet $TRAVIS_BUILD_DIR/target/the-buyback*.war $USER@$HOST:~/thebuyback_$(date +%m-%d-%y-%H-%M).war
  on:
    branch: master
env:
  secure: C88D/g3gTT6hFkETM9q81gcsFg+4Bup9LyrhLiDAcPdJzlIIvLtLGeEybqfyOEuXH7ED6GHP5PmLHtDtwlPcfdrWqy3qn9N3fXwtMcVmaNV83Wxwj3mmAlhas0EsU3RNkmlXJ2MsyEPHi7BbSYkrKOE+ZvL8lI0nbFCdVvdWHoFlsIJJdIpnWjQ+YHAn/KosRp6waC3drDe0zg0ryl28ytm6N0YMbtEfHhOGQL47SKnDtoCQfofkmygGe+jrdWFecspQVYCxFW/Hn6CKAR+iFj7ZkTMZ35EgP7gVVCv4QGe64NrWXhbn9rtZSV5cnR90tAKU7+wVfFugH7EQZ9LBaPJBSP8gBjmB2EYIM2jqii5SwCLIgwROvpTfK+FiWkYBtvrDlqSTLWeOQ0a4LADJcQcsWCYujQHBvtiMUlhW4wbvpTILKk7iOuLcTgt0Fj+GSDOwS5oGte6mBhb7hNB1O+nkaHKj0dfE9fakNaM3mpB56HTeDKvH6kml5s/Q2IEg+/+3EUSup/K3Q6ZEN2WvMQ7Omb6AsxgNXzBD6/hY339a4e91oRe+wyp8/6qK4JlEnNO1ahsyePIbxFA3VPKykAPHzOwYwP9hLJugwuO15kmCRUI1YuFuC4TwMep2D6NdYqEQTCso5Dkuujo7bDlEBh1k0Nihed2tMSuWFMWwvSc=
