version: '2'
services:
    thebuyback-app:
        image: thebuyback
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://thebuyback-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=thebuyback
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    thebuyback-mongodb:
        extends:
            file: mongodb.yml
            service: thebuyback-mongodb
