version: '2'
services:
    braveBucks-app:
        image: braveBucks
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://braveBucks-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=braveBucks
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    braveBucks-mongodb:
        extends:
            file: mongodb.yml
            service: braveBucks-mongodb
